ProjectSerial: ParSet.c Project-serial.c
        gcc -I/homes/cwalrus96/project -c ParSet.c Project-serial.c
        gcc -L/homes/cwalrus96/project ParSet.o Project-serial.o \
        -llammps -lfftw -lmpi -lpthread -lstdc++ -lm -o ProjectSerial
